### ISSUE TITLE
When I press start this shows up and after that it does not work

### ISSUE THREAD

**Issue by demoncode-cyber** [assassinsorrow/PyRhythm#2]
src.Modules.FirstRun, 69 || 2020-12-30 01:14:26,869 :: INFO :: has been run before carrying on
src.__main__, 218 || 2020-12-30 01:14:28,936 :: ERROR :: Something went wrong while starting window capture
Traceback (most recent call last):
  File "C:\Users\Me\OneDrive\Desktop\Modding\RhythmPy-master\RhythmPy\src\__main__.py", line 214, in ManiaStart
    Wincap = WindowCapture(None)
NameError: name 'WindowCapture' is not defined
src.__main__, 273 || 2020-12-30 01:14:28,936 :: INFO :: Started Thread for Bot

**Comment by ShyAssassin** [comment]
What version of python are you using to run the project?

**Comment by demoncode-cyber** [comment]
3.6

**Comment by ShyAssassin** [comment]
i have found the problem i will fix it in the next update
for now run with __main__.py in src

**Comment by ShyAssassin** [comment]
`__main__.py` in src

**Comment by demoncode-cyber** [comment]
okok thank you
