### ISSUE TITLE
pywin32 isnt included in the dependencies

### ISSUE THREAD

**Issue by Af7eR9l0W** [assassinsorrow/PyRhythm#6]
Howdy. After running through your instruction, i noticed terminal spitting out its missing win32gui, which is a part of pywin32. Opening the .lock files and ctr+f also shows that its missing.  This problem is circumvented by just ignoring the poetry step and using your own python venv. 

**To Reproduce**
1. Go to '~/usr/goob/home/'RhythmPy-master/Rhythm-py
2. Click on 'poetry run python __main__.py'
3. Scroll down to 'First input'

Expected it to run lol
![image](https://user-images.githubusercontent.com/85209771/121372696-19830080-c904-11eb-8225-c7830b5de91b.png)
and inside the poetry dependency installer
![image](https://user-images.githubusercontent.com/85209771/121372912-41726400-c904-11eb-8eb3-8c6cee42d96e.png)

**Desktop (please complete the following information):**
 - OS: windows 10/Arch/Ubuntu
 - Browser chrome
 - Version latest

Easy fix

**Comment by ShyAssassin** [comment]
Thank you for noticing this problem,
I will update the documentation quick.
For the time being you can install it by using 'poetry install -E Windows -E pyinstaller'
